#let algorithm-entries = (
  (name: "并查集／DSU", function: "连通关系维护（并查集）", chapter: "数据结构与区间查询", target: <book-dsu>),
  (name: "按大小合并", function: "按大小合并", chapter: "数据结构与区间查询", target: <book-variant-001>),
  (name: "带权并查集", function: "带权并查集", chapter: "数据结构与区间查询", target: <book-variant-002>),
  (name: "可撤销并查集", function: "可撤销并查集", chapter: "数据结构与区间查询", target: <book-variant-003>),
  (name: "倍增并查集", function: "倍增并查集", chapter: "数据结构与区间查询", target: <book-variant-004>),
  (name: "树状数组／Fenwick", function: "前缀与区间统计（树状数组）", chapter: "数据结构与区间查询", target: <book-fenwick>),
  (name: "前缀和配对", function: "区间和与同余计数（前缀配对）", chapter: "数据结构与区间查询", target: <book-prefix-pairs>),
  (name: "Sparse Table／ST 表", function: "静态区间查询（稀疏表）", chapter: "数据结构与区间查询", target: <book-sparse>),
  (name: "Disjoint Sparse Table", function: "静态区间查询（稀疏表）", chapter: "数据结构与区间查询", target: <book-sparse>),
  (name: "线段树／Segment Tree", function: "区间修改与查询（线段树）", chapter: "数据结构与区间查询", target: <book-segment>),
  (name: "维护区间和，支持区间加、区间查询", function: "维护区间和，支持区间加、区间查询", chapter: "数据结构与区间查询", target: <book-variant-010>),
  (name: "维护区间最大值，支持区间加、区间查询", function: "维护区间最大值，支持区间加、区间查询", chapter: "数据结构与区间查询", target: <book-variant-011>),
  (name: "维护区间和，支持区间加、区间乘、区间查询", function: "维护区间和，支持区间加、区间乘、区间查询", chapter: "数据结构与区间查询", target: <book-variant-012>),
  (name: "动态开点，维护区间和，支持区间加、区间查询", function: "动态开点，维护区间和，支持区间加、区间查询", chapter: "数据结构与区间查询", target: <book-variant-013>),
  (name: "维护区间 GCD，支持区间加、区间查询", function: "维护区间 GCD，支持区间加、区间查询", chapter: "数据结构与区间查询", target: <book-variant-014>),
  (name: "区间第 k 小", function: "区间第 k 小", chapter: "数据结构与区间查询", target: <book-range-kth>),
  (name: "主席树／可持久化线段树", function: "静态查询：主席树", chapter: "数据结构与区间查询", target: <book-persistent-kth>),
  (name: "整体二分", function: "带修改查询：整体二分", chapter: "数据结构与区间查询", target: <book-parallel-binary>),
  (name: "离线区间统计", function: "离线区间统计", chapter: "数据结构与区间查询", target: <book-offline-range>),
  (name: "区间不同数／离线扫描", function: "不同数查询：离线扫描", chapter: "数据结构与区间查询", target: <book-distinct-scan>),
  (name: "莫队／Mo", function: "可增删贡献：莫队", chapter: "数据结构与区间查询", target: <book-mo>),
  (name: "Hilbert 序莫队", function: "Hilbert 序莫队", chapter: "数据结构与区间查询", target: <book-variant-021>),
  (name: "阈值查询／排序激活", function: "阈值查询（排序激活）", chapter: "数据结构与区间查询", target: <book-threshold-scan>),
  (name: "CDQ 分治／三维偏序", function: "多维偏序计数（CDQ）", chapter: "数据结构与区间查询", target: <book-cdq>),
  (name: "FHQ Treap", function: "有序集合、排名与前后驱（FHQ Treap）", chapter: "数据结构与区间查询", target: <book-treap>),
  (name: "对顶堆／动态中位数", function: "动态中位数（对顶堆）", chapter: "数据结构与区间查询", target: <book-median-heaps>),
  (name: "左偏树／可并堆", function: "可合并优先队列（左偏树）", chapter: "数据结构与区间查询", target: <book-leftist>),
  (name: "李超树／Li Chao Tree", function: "直线最值查询（李超树）", chapter: "数据结构与区间查询", target: <book-li-chao>),
  (name: "权值线段树合并", function: "值域结构合并（权值线段树合并）", chapter: "数据结构与区间查询", target: <book-segment-merge>),
  (name: "01 Trie／二进制字典树", function: "最大异或与全局异或标记（01 Trie）", chapter: "数据结构与区间查询", target: <book-xor-trie>),
  (name: "线性基／XOR Basis", function: "子集异或可达性与排名（线性基）", chapter: "数据结构与区间查询", target: <book-xor-basis>),
  (name: "前缀异或／区间 XOR", function: "区间异或与前缀配对", chapter: "数据结构与区间查询", target: <book-prefix-xor>),
  (name: "按位贡献／异或总和", function: "异或总和的按位贡献", chapter: "数据结构与区间查询", target: <book-xor-contribution>),
  (name: "区间 AND／OR／GCD 状态压缩", function: "AND／OR／GCD 区间结果压缩", chapter: "数据结构与区间查询", target: <book-compressed-intervals>),
  (name: "按位贪心／AND 最优值", function: "按位约束最优值（高位贪心）", chapter: "数据结构与区间查询", target: <book-bit-greedy>),
  (name: "动态位集／Dynamic Bitset", function: "批量集合运算（动态位集）", chapter: "数据结构与区间查询", target: <book-bitset>),
  (name: "双栈聚合队列", function: "滑动队列的结合聚合（双栈）", chapter: "数据结构与区间查询", target: <book-aggregate-queue>),
  (name: "堆的懒删除", function: "带删除的优先队列（懒删除）", chapter: "数据结构与区间查询", target: <book-lazy-heap>),
  (name: "全局加减／偏移量", function: "全局加减维护（偏移量）", chapter: "数据结构与区间查询", target: <book-global-offset>),
  (name: "平方和／矩统计", function: "二次统计量维护（矩与贡献）", chapter: "数据结构与区间查询", target: <book-moments>),
  (name: "高阶差分", function: "批量区间更新（高阶差分）", chapter: "数据结构与区间查询", target: <book-higher-difference>),
  (name: "区间扫描线／端点语义", function: "区间覆盖与端点扫描", chapter: "数据结构与区间查询", target: <book-interval-sweep>),
  (name: "DFS 序／进入退出时间", function: "子树区间与祖先判断（DFS 序）", chapter: "树上问题", target: <book-dfs-order>),
  (name: "LCA／最近公共祖先", function: "最近公共祖先（LCA）", chapter: "树上问题", target: <book-lca>),
  (name: "倍增求 LCA", function: "倍增求 LCA", chapter: "树上问题", target: <book-variant-044>),
  (name: "Tarjan 离线求 LCA", function: "Tarjan 离线求 LCA", chapter: "树上问题", target: <book-variant-045>),
  (name: "树链剖分求 LCA", function: "树链剖分求 LCA", chapter: "树上问题", target: <book-variant-046>),
  (name: "欧拉序与 RMQ 求 LCA", function: "欧拉序与 RMQ 求 LCA", chapter: "树上问题", target: <book-variant-047>),
  (name: "树链剖分／HLD", function: "路径与子树查询（树链剖分）", chapter: "树上问题", target: <book-hld>),
  (name: "树上莫队／进出欧拉序", function: "树上路径离线统计（欧拉序莫队）", chapter: "树上问题", target: <book-tree-mo>),
  (name: "树上点差分／边差分", function: "批量路径更新（树上差分）", chapter: "树上问题", target: <book-tree-difference>),
  (name: "换根 DP／Rerooting", function: "全根统计（换根 DP）", chapter: "树上问题", target: <book-reroot>),
  (name: "树上距离和／按边贡献", function: "全点对距离与分支贡献", chapter: "树上问题", target: <book-tree-distance-sum>),
  (name: "点分治／重心分解", function: "树上距离约束统计（点分治）", chapter: "树上问题", target: <book-centroid>),
  (name: "树直径／点集直径合并", function: "最远点与点集直径", chapter: "树上问题", target: <book-tree-diameter>),
  (name: "虚树／Virtual Tree", function: "少量关键点构树（虚树）", chapter: "树上问题", target: <book-virtual-tree>),
  (name: "树形 DP／连通块计数", function: "树上连通块计数（树形 DP）", chapter: "树上问题", target: <book-tree-connected-dp>),
  (name: "树上背包／依赖背包", function: "树上背包与依赖选择", chapter: "树上问题", target: <book-tree-knapsack>),
  (name: "DSU on Tree／启发式合并", function: "子树集合统计（启发式合并）", chapter: "树上问题", target: <book-dsu-on-tree>),
  (name: "树同构", function: "树同构判定", chapter: "树上问题", target: <book-tree-isomorphism>),
  (name: "Link-Cut Tree／LCT", function: "动态森林路径查询（Link-Cut Tree）", chapter: "树上问题", target: <book-lct>),
  (name: "Euler Tour Tree／ETT", function: "动态森林连通块统计（Euler Tour Tree）", chapter: "树上问题", target: <book-ett>),
  (name: "静态拓扑 Top Tree", function: "单边改权维护直径（静态拓扑 Top Tree）", chapter: "树上问题", target: <book-top-tree>),
  (name: "Prüfer 序列", function: "树的编码与计数（Prüfer 序列）", chapter: "树上问题", target: <book-prufer>),
  (name: "最短路", function: "最短路径", chapter: "图论", target: <book-shortest-path>),
  (name: "Dijkstra", function: "单源非负权：Dijkstra", chapter: "图论", target: <book-dijkstra>),
  (name: "Floyd", function: "全点对：Floyd", chapter: "图论", target: <book-floyd>),
  (name: "线段树优化建图", function: "区间连边（线段树优化建图）", chapter: "图论", target: <book-range-graph>),
  (name: "差分约束", function: "差分不等式可行性（差分约束）", chapter: "图论", target: <book-difference-constraints>),
  (name: "SCC／Tarjan 缩点", function: "有向图强连通分量与缩点（Tarjan）", chapter: "图论", target: <book-scc>),
  (name: "割点／桥／双连通分量", function: "删点删边连通性与双连通分量", chapter: "图论", target: <book-bcc>),
  (name: "割点", function: "割点", chapter: "图论", target: <book-articulation>),
  (name: "桥", function: "桥", chapter: "图论", target: <book-bridge>),
  (name: "边双连通分量", function: "边双连通分量", chapter: "图论", target: <book-edge-bcc>),
  (name: "点双连通分量", function: "点双连通分量", chapter: "图论", target: <book-vertex-bcc>),
  (name: "最小生成树／MST", function: "最小生成树（MST）", chapter: "图论", target: <book-mst>),
  (name: "set 优化 Prim", function: "set 优化 Prim", chapter: "图论", target: <book-variant-076>),
  (name: "堆优化 Prim", function: "堆优化 Prim", chapter: "图论", target: <book-variant-077>),
  (name: "Kruskal", function: "Kruskal", chapter: "图论", target: <book-variant-078>),
  (name: "Borůvka 异或最小生成树", function: "Borůvka 异或最小生成树", chapter: "图论", target: <book-variant-079>),
  (name: "严格次小生成树", function: "严格次小生成树", chapter: "图论", target: <book-variant-080>),
  (name: "Kruskal 重构树", function: "阈值连通性（Kruskal 重构树）", chapter: "图论", target: <book-kruskal-tree>),
  (name: "Matrix Tree／矩阵树定理", function: "生成树计数（矩阵树定理）", chapter: "图论", target: <book-matrix-tree>),
  (name: "2-SAT", function: "二变量逻辑约束（2-SAT）", chapter: "图论", target: <book-two-sat>),
  (name: "支配树／Dominator Tree", function: "必经点与支配关系（支配树）", chapter: "图论", target: <book-dominator>),
  (name: "欧拉路／欧拉回路", function: "一次经过每条边（欧拉路）", chapter: "图论", target: <book-euler-route>),
  (name: "线段树分治／动态连通性", function: "动态连通性（时间线段树与可撤销并查集）", chapter: "图论", target: <book-dynamic-connectivity>),
  (name: "最大匹配", function: "最大匹配", chapter: "图论", target: <book-matching>),
  (name: "二分图匹配", function: "二分图最大匹配", chapter: "图论", target: <book-bipartite-matching>),
  (name: "一般图匹配／Blossom", function: "一般图最大匹配（带花树）", chapter: "图论", target: <book-blossom>),
  (name: "拟阵交／Matroid Intersection", function: "同时满足两类独立约束（拟阵交）", chapter: "图论", target: <book-matroid>),
  (name: "增广框架", function: "增广框架", chapter: "图论", target: <book-variant-091>),
  (name: "划分拟阵与图拟阵", function: "划分拟阵与图拟阵", chapter: "图论", target: <book-variant-092>),
  (name: "功能图／Functional Graph", function: "单出边图上的跳转与环（功能图）", chapter: "图论", target: <book-functional-graph>),
  (name: "基环树／剥叶找环", function: "无向单环结构（基环树）", chapter: "图论", target: <book-unicyclic>),
  (name: "图上邻居加／根号分治", function: "邻居批量更新（高低度根号分治）", chapter: "图论", target: <book-graph-neighbor>),
  (name: "最大流", function: "最大流", chapter: "网络流", target: <book-max-flow>),
  (name: "EK", function: "EK 增广路", chapter: "网络流", target: <book-ek>),
  (name: "Dinic", function: "Dinic 分层增广", chapter: "网络流", target: <book-dinic>),
  (name: "最小割／源汇划分", function: "最小割与划分恢复", chapter: "网络流", target: <book-min-cut>),
  (name: "最小割的最少边数", function: "最小容量后的最少割边", chapter: "网络流", target: <book-min-cut-edges>),
  (name: "最小费用最大流", function: "最小费用最大流", chapter: "网络流", target: <book-min-cost-flow>),
  (name: "SPFA 最小费用最大流", function: "SPFA 最小费用最大流", chapter: "网络流", target: <book-spfa-cost-flow>),
  (name: "势能 Dijkstra 最小费用最大流", function: "势能 Dijkstra 最小费用最大流", chapter: "网络流", target: <book-potential-cost-flow>),
  (name: "有上下界可行流", function: "上下界可行流", chapter: "网络流", target: <book-bounded-flow>),
  (name: "背包／Knapsack", function: "背包选择", chapter: "动态规划", target: <book-knapsack>),
  (name: "bitset 背包", function: "布尔可达性与方案恢复（bitset 背包）", chapter: "动态规划", target: <book-bitset-knapsack>),
  (name: "最长上升子序列／LIS", function: "序列最优值与前驱重建（LIS）", chapter: "动态规划", target: <book-lis>),
  (name: "偏序 DP／同值批量查询", function: "偏序约束下的最优序列", chapter: "动态规划", target: <book-partial-order-dp>),
  (name: "状态压缩／支配状态", function: "状态等价、守恒与支配关系", chapter: "动态规划", target: <book-dp-state>),
  (name: "贡献提前计算", function: "未来成本的提前结算", chapter: "动态规划", target: <book-dp-advance-cost>),
  (name: "DP 前缀和优化", function: "区间求和转移（前缀和）", chapter: "动态规划", target: <book-dp-prefix>),
  (name: "DP 单调队列优化", function: "滑动窗口最优转移（单调队列）", chapter: "动态规划", target: <book-dp-monotone-queue>),
  (name: "绝对值 DP／两侧最值", function: "绝对值与两侧代价转移", chapter: "动态规划", target: <book-dp-two-sides>),
  (name: "区间 DP／环形 DP", function: "区间合并与消除", chapter: "动态规划", target: <book-interval-dp>),
  (name: "Knuth 优化／石子合并", function: "区间切点优化（Knuth）", chapter: "动态规划", target: <book-knuth>),
  (name: "双路径同步 DP", function: "同步多路径状态", chapter: "动态规划", target: <book-synchronous-path-dp>),
  (name: "状压 DP／集合分组", function: "集合分组与子集状态", chapter: "动态规划", target: <book-subset-dp>),
  (name: "轮廓 DP／插头状态", function: "窄网格边界状态（轮廓 DP）", chapter: "动态规划", target: <book-contour-dp>),
  (name: "数位 DP／Digit DP", function: "数字范围计数（数位 DP）", chapter: "动态规划", target: <book-digit-dp>),
  (name: "最优方案计数", function: "最优值与方案数共同维护", chapter: "动态规划", target: <book-optimal-count>),
  (name: "斜率优化／Convex Hull Trick", function: "直线型转移（斜率优化）", chapter: "动态规划", target: <book-cht-dp>),
  (name: "分治优化 DP", function: "决策单调的分治优化", chapter: "动态规划", target: <book-divide-conquer-dp>),
  (name: "WQS 二分／Aliens Trick", function: "恰好 K 次选择（WQS 二分）", chapter: "动态规划", target: <book-wqs>),
  (name: "Slope Trick", function: "凸分段线性代价（Slope Trick）", chapter: "动态规划", target: <book-slope-trick>),
  (name: "连续段 DP", function: "按值插入的连续段状态", chapter: "动态规划", target: <book-continuous-segments-dp>),
  (name: "矩阵加速 DP", function: "有限状态的巨大步数转移（矩阵加速）", chapter: "动态规划", target: <book-matrix-dp>),
  (name: "DAG DP／拓扑序计数", function: "有向无环状态图（DAG DP）", chapter: "动态规划", target: <book-dag-dp>),
  (name: "字符串哈希／String Hash", function: "子串相等性（字符串哈希）", chapter: "字符串", target: <book-string-hash>),
  (name: "KMP／前缀函数", function: "单模式匹配（KMP）", chapter: "字符串", target: <book-kmp>),
  (name: "Z 函数／扩展 KMP", function: "前缀匹配长度（Z 函数）", chapter: "字符串", target: <book-z-function>),
  (name: "AC 自动机／ACAM", function: "多模式匹配（AC 自动机）", chapter: "字符串", target: <book-ac>),
  (name: "Manacher", function: "最长回文半径（Manacher）", chapter: "字符串", target: <book-manacher>),
  (name: "后缀数组／SA／LCP", function: "后缀排序与最长公共前缀（SA／LCP）", chapter: "字符串", target: <book-suffix-array>),
  (name: "后缀自动机／SAM", function: "子串集合与出现次数（SAM）", chapter: "字符串", target: <book-sam>),
  (name: "Lyndon 分解／Duval／最小循环表示", function: "字典序因子分解与最小循环表示（Lyndon）", chapter: "字符串", target: <book-lyndon>),
  (name: "runs／极大周期串", function: "极大周期区间（runs）", chapter: "字符串", target: <book-runs>),
  (name: "Trie／字符串字典树", function: "单词与前缀集合（Trie）", chapter: "字符串", target: <book-string-trie>),
  (name: "快速幂／模乘", function: "模幂与防溢出模乘", chapter: "数论", target: <book-mod-power>),
  (name: "普通快速幂", function: "普通快速幂", chapter: "数论", target: <book-binary-power>),
  (name: "快速乘", function: "快速乘", chapter: "数论", target: <book-variant-140>),
  (name: "龟速乘", function: "龟速乘", chapter: "数论", target: <book-variant-141>),
  (name: "EXGCD／扩展欧几里得", function: "整数线性方程（扩展欧几里得）", chapter: "数论", target: <book-exgcd>),
  (name: "求 a x + b y = c 的解", function: "求 a x + b y = c 的解", chapter: "数论", target: <book-variant-143>),
  (name: "模逆元／模除法／批量逆元", function: "模逆元与模除法", chapter: "数论", target: <book-mod-inverse>),
  (name: "CRT／EXCRT", function: "同余方程组合（EXCRT）", chapter: "数论", target: <book-excrt>),
  (name: "扩展欧拉定理", function: "复合模指数降幂（扩展欧拉）", chapter: "数论", target: <book-extended-euler>),
  (name: "BSGS／EXBSGS", function: "离散对数（扩展 BSGS）", chapter: "数论", target: <book-exbsgs>),
  (name: "线性筛／欧拉筛", function: "质数与积性函数预处理（线性筛）", chapter: "数论", target: <book-linear-sieve>),
  (name: "筛质数", function: "筛质数", chapter: "数论", target: <book-variant-149>),
  (name: "筛积性函数", function: "筛积性函数", chapter: "数论", target: <book-variant-150>),
  (name: "Pollard-Rho／Miller-Rabin", function: "整数分解与质因子指数（Pollard-Rho）", chapter: "数论", target: <book-pollard-rho>),
  (name: "整除分块", function: "整除商的批量求和（整除分块）", chapter: "数论", target: <book-division-block>),
  (name: "因子枚举／倍数贡献", function: "因子与倍数贡献交换", chapter: "数论", target: <book-divisor-contribution>),
  (name: "莫比乌斯反演", function: "互质计数（莫比乌斯反演）", chapter: "数论", target: <book-mobius>),
  (name: "杜教筛", function: "积性函数大范围前缀和（杜教筛）", chapter: "数论", target: <book-dujiao>),
  (name: "Min_25 筛", function: "积性函数大范围求和（Min_25 筛）", chapter: "数论", target: <book-min25>),
  (name: "类欧几里得／floor_sum", function: "线性取整求和（类欧几里得）", chapter: "数论", target: <book-floor-sum>),
  (name: "floor_sum", function: "floor_sum", chapter: "数论", target: <book-variant-158>),
  (name: "高阶类欧（精确值）", function: "高阶类欧（精确值）", chapter: "数论", target: <book-variant-159>),
  (name: "高阶类欧（取模）", function: "高阶类欧（取模）", chapter: "数论", target: <book-variant-160>),
  (name: "矩阵乘法／矩阵快速幂", function: "矩阵运算与快速幂", chapter: "线性代数", target: <book-matrix-power>),
  (name: "矩阵快速幂（独立接口）", function: "旧版矩阵快速幂接口", chapter: "线性代数", target: <book-legacy-matrix-power>),
  (name: "高斯消元／Gauss", function: "线性方程组、行列式与逆矩阵（消元）", chapter: "线性代数", target: <book-linear-system>),
  (name: "行列式／逆矩阵", function: "线性方程组、行列式与逆矩阵（消元）", chapter: "线性代数", target: <book-linear-system>),
  (name: "线性方程组解的分类", function: "高斯消元与解的分类", chapter: "线性代数", target: <book-gauss>),
  (name: "矩阵求逆／唯一解", function: "行列式、逆矩阵与唯一解接口", chapter: "线性代数", target: <book-matrix-inverse>),
  (name: "组合数／Lucas／任意模组合数", function: "组合数计算", chapter: "组合计数", target: <book-combination>),
  (name: "阶乘预处理与批量逆元", function: "阶乘预处理与批量逆元", chapter: "组合计数", target: <book-variant-168>),
  (name: "Lucas 定理", function: "Lucas 定理", chapter: "组合计数", target: <book-variant-169>),
  (name: "任意模数下的组合数", function: "任意模数下的组合数", chapter: "组合计数", target: <book-variant-170>),
  (name: "隔板法／Stars and Bars", function: "分配与有界拆分（隔板法）", chapter: "组合计数", target: <book-stars-bars>),
  (name: "容斥原理／补集计数", function: "非法方案的容斥与补集", chapter: "组合计数", target: <book-inclusion-exclusion>),
  (name: "整数拆分／五边形递推", function: "整数拆分与常见计数序列", chapter: "组合计数", target: <book-combinatorial-numbers>),
  (name: "卡特兰数／Catalan", function: "整数拆分与常见计数序列", chapter: "组合计数", target: <book-combinatorial-numbers>),
  (name: "斯特林数／Stirling", function: "整数拆分与常见计数序列", chapter: "组合计数", target: <book-combinatorial-numbers>),
  (name: "贝尔数／Bell", function: "整数拆分与常见计数序列", chapter: "组合计数", target: <book-combinatorial-numbers>),
  (name: "欧拉数／Eulerian", function: "整数拆分与常见计数序列", chapter: "组合计数", target: <book-combinatorial-numbers>),
  (name: "正整数有序拆分", function: "正整数有序拆分", chapter: "组合计数", target: <book-ordered-partition>),
  (name: "错排／Derangement／排列环计数", function: "排列的固定点、错排与环", chapter: "组合计数", target: <book-permutation-counting>),
  (name: "康托展开", function: "排列排名与还原（康托展开）", chapter: "组合计数", target: <book-cantor>),
  (name: "Burnside／Pólya", function: "对称等价方案计数（Burnside／Pólya）", chapter: "组合计数", target: <book-burnside>),
  (name: "生成函数／OGF／EGF", function: "计数模型的生成函数", chapter: "组合计数", target: <book-generating-function>),
  (name: "概率／期望", function: "概率与期望的基本模型", chapter: "概率与期望", target: <book-probability-basics>),
  (name: "指示变量／期望线性性", function: "总数量与总得分（指示变量）", chapter: "概率与期望", target: <book-indicator-expectation>),
  (name: "尾和公式／几何等待", function: "随机长度与等待次数", chapter: "概率与期望", target: <book-tail-expectation>),
  (name: "概率 DP", function: "随机过程的分布（概率 DP）", chapter: "概率与期望", target: <book-probability-dp>),
  (name: "自环期望 DP", function: "含原地等待的期望方程（自环）", chapter: "概率与期望", target: <book-self-loop-expectation>),
  (name: "SG 函数／Sprague-Grundy／Nim", function: "Nim 与无环游戏的 SG 模型", chapter: "博弈论", target: <book-sg>),
  (name: "反 Nim／Misère Nim", function: "反常终止（反 Nim）", chapter: "博弈论", target: <book-misere-nim>),
  (name: "巴什博弈", function: "固定上限取石子（巴什）", chapter: "博弈论", target: <book-bash>),
  (name: "对称策略／策略偷换", function: "对称应手与策略偷换", chapter: "博弈论", target: <book-symmetric-game>),
  (name: "阶梯 Nim", function: "相邻层下移（阶梯 Nim）", chapter: "博弈论", target: <book-staircase-nim>),
  (name: "Silver Dollar／棋子间隙博弈", function: "受阻棋子移动（Silver Dollar）", chapter: "博弈论", target: <book-silver-dollar>),
  (name: "威佐夫博弈／Wythoff", function: "双堆同步取石子（威佐夫）", chapter: "博弈论", target: <book-wythoff>),
  (name: "Fibonacci Nim", function: "行动上限随步骤变化（Fibonacci Nim）", chapter: "博弈论", target: <book-fibonacci-nim>),
  (name: "有环博弈／胜负平局", function: "可循环的胜负与平局（反图传播）", chapter: "博弈论", target: <book-loopy-game>),
  (name: "有偏博弈／行动者状态", function: "双方规则不同的轮流博弈", chapter: "博弈论", target: <book-player-state>),
  (name: "minimax／得分博弈", function: "得分最大化对抗（minimax）", chapter: "博弈论", target: <book-minimax>),
  (name: "树上删边博弈", function: "树上删边游戏", chapter: "博弈论", target: <book-tree-game>),
  (name: "奇偶策略／博弈规律验证", function: "奇偶势与胜负规律证明", chapter: "博弈论", target: <book-game-invariant>),
  (name: "卷积／Convolution", function: "普通卷积（FFT／NTT）", chapter: "多项式与卷积", target: <book-convolution>),
  (name: "FFT", function: "FFT", chapter: "多项式与卷积", target: <book-fft>),
  (name: "NTT", function: "NTT", chapter: "多项式与卷积", target: <book-ntt>),
  (name: "SOS／Zeta／Möbius／FWT", function: "掩码上的子集和与位运算卷积（Zeta／FWT）", chapter: "多项式与卷积", target: <book-subset-transform>),
  (name: "子集卷积", function: "不相交集合合并（子集卷积）", chapter: "多项式与卷积", target: <book-subset-convolution>),
  (name: "多项式基础运算", function: "多项式基础运算与 NTT 接口", chapter: "多项式与卷积", target: <book-poly-base>),
  (name: "多项式求逆", function: "形式幂级数求逆", chapter: "多项式与卷积", target: <book-poly-inverse>),
  (name: "多项式 ln／exp", function: "形式幂级数对数与指数", chapter: "多项式与卷积", target: <book-poly-log-exp>),
  (name: "多项式 sqrt", function: "形式幂级数平方根", chapter: "多项式与卷积", target: <book-poly-sqrt>),
  (name: "多项式除法", function: "多项式除法与余数", chapter: "多项式与卷积", target: <book-poly-div>),
  (name: "多项式 pow", function: "形式幂级数幂", chapter: "多项式与卷积", target: <book-poly-power>),
  (name: "多点求值／插值", function: "多点求值与插值", chapter: "多项式与卷积", target: <book-multipoint>),
  (name: "拉格朗日插值／Lagrange", function: "单点插值求值（拉格朗日）", chapter: "多项式与卷积", target: <book-lagrange>),
  (name: "Berlekamp-Massey／BM", function: "从前若干项恢复最短递推（BM）", chapter: "线性递推", target: <book-bm>),
  (name: "Bostan-Mori", function: "线性递推第 n 项（Bostan-Mori）", chapter: "线性递推", target: <book-bostan-mori>),
  (name: "几何选型／区域赛样本", function: "读题信号与区域赛样本", chapter: "计算几何", target: <book-geometric-models>),
  (name: "点与直线／叉积／点积／atan2", function: "点线基础与夹角计算", chapter: "计算几何", target: <book-point-line>),
  (name: "线段相交／点在多边形内", function: "线段相交与多边形包含", chapter: "计算几何", target: <book-segments-polygon>),
  (name: "半平面交／HPI", function: "半平面约束交集", chapter: "计算几何", target: <book-half-plane-intersection>),
  (name: "圆相交／公切线／交面积", function: "圆的交点、切线与交面积", chapter: "计算几何", target: <book-circle>),
  (name: "极角排序／开闭半圆／覆盖角宽", function: "圆周方向统计（极角排序与扫描）", chapter: "计算几何", target: <book-polar-scan>),
  (name: "凸包／旋转卡壳／凸多边形点定位", function: "凸包极值与点定位（旋转卡壳）", chapter: "计算几何", target: <book-convex-hull>),
  (name: "鞋带公式／有向面积／面积贡献", function: "多边形面积与面积总和（有向边贡献）", chapter: "计算几何", target: <book-geometric-area>),
  (name: "矩形面积并／扫描线", function: "矩形面积并（扫描线）", chapter: "计算几何", target: <book-rectangle-union>),
  (name: "Minkowski／闵可夫斯基和／差", function: "平移碰撞（闵可夫斯基和／差）", chapter: "计算几何", target: <book-minkowski>),
  (name: "几何概率／重叠面积期望", function: "几何概率与随机重叠面积", chapter: "计算几何", target: <book-geometric-probability>),
  (name: "面积重心／仿射重心", function: "面积重心与随机配重", chapter: "计算几何", target: <book-centroid-area>),
  (name: "仿射变换／行列式与面积", function: "坐标变换后的几何不变量", chapter: "计算几何", target: <book-affine-transform>),
  (name: "格点构造／整点中点", function: "整点中点的可达性与最少步数", chapter: "计算几何", target: <book-lattice-midpoint>),
  (name: "曼哈顿距离／切比雪夫距离／坐标变换", function: "曼哈顿与切比雪夫距离", chapter: "计算几何", target: <book-metric-transform>),
  (name: "三角形不等式／边长判定", function: "三角形边长的可行性", chapter: "计算几何", target: <book-triangle-inequality>),
  (name: "角点／极端点／有限见证集", function: "少量图形覆盖（有限见证集）", chapter: "计算几何", target: <book-finite-geometry>),
  (name: "局部最低平台／谷底", function: "地形局部最低区域", chapter: "计算几何", target: <book-local-minima>),
  (name: "反射／镜面展开／转角周期", function: "镜面反射路径与周期", chapter: "计算几何", target: <book-reflection>),
  (name: "首次碰撞树／平面区域计数", function: "碰撞结构与平面分割", chapter: "计算几何", target: <book-planar-topology>),
  (name: "几何 eps／分数交点／退化处理", function: "数值谓词、精确交点与退化处理", chapter: "计算几何", target: <book-geometry-robustness>),
  (name: "几何代码依赖与复杂度", function: "几何代码依赖与接口约定", chapter: "计算几何", target: <book-geometry-practice>),
  (name: "高精度／BigInt", function: "带符号大整数运算", chapter: "工具与通用技巧", target: <book-bigint>),
  (name: "i128／宽整数防溢出", function: "宽整数运算与输入输出（i128）", chapter: "工具与通用技巧", target: <book-wide-integer>),
  (name: "置位遍历／popcount／有限位域", function: "位枚举、进位与有限位域", chapter: "工具与通用技巧", target: <book-bit-operations>),
  (name: "归并排序／逆序对", function: "排序与逆序对（归并排序）", chapter: "工具与通用技巧", target: <book-merge-sort>),
  (name: "三分搜索", function: "单峰最优值（三分）", chapter: "工具与通用技巧", target: <book-ternary-search>),
  (name: "折半搜索／Meet in the Middle", function: "指数规模搜索（折半）", chapter: "工具与通用技巧", target: <book-meet-in-middle>),
  (name: "随机指纹", function: "随机集合指纹", chapter: "工具与通用技巧", target: <book-fingerprint>),
  (name: "双指针／滑动窗口／最短达标段", function: "连续区间可行性（双指针与单调队列）", chapter: "工具与通用技巧", target: <book-window>),
  (name: "隐式第 k 小／候选区间拆分", function: "隐式第 k 小与第 k 大", chapter: "工具与通用技巧", target: <book-implicit-order>),
  (name: "二分答案／比例最优", function: "单调判定与比值最优（二分答案）", chapter: "工具与通用技巧", target: <book-binary-answer>),
  (name: "反悔贪心／任务排序", function: "截止时间调度与反悔贪心", chapter: "工具与通用技巧", target: <book-scheduling>),
  (name: "三元组计数／固定中间元素", function: "按中间元素统计三元组", chapter: "工具与通用技巧", target: <book-triple-contribution>),
  (name: "全点对绝对差总和", function: "全点对绝对差总和（排序贡献）", chapter: "工具与通用技巧", target: <book-pair-absolute-difference>),
  (name: "最少交换次数／排列环／同类元素聚拢", function: "最少交换次数", chapter: "工具与通用技巧", target: <book-minimum-swaps>),
  (name: "局部修改／区间反转增量", function: "局部修改的增量维护", chapter: "工具与通用技巧", target: <book-local-change>),
  (name: "区间支配／区间选择", function: "区间选择中的支配删除", chapter: "工具与通用技巧", target: <book-dominated-intervals>),
  (name: "不交叉区间树／层级结构", function: "不交叉区间构树", chapter: "工具与通用技巧", target: <book-interval-tree>),
  (name: "根号分治／高低频成本", function: "高低频分治的总成本", chapter: "工具与通用技巧", target: <book-sqrt-cost>),
  (name: "字典序最小／可行性构造", function: "字典序最小的逐步构造", chapter: "工具与通用技巧", target: <book-lexicographic-construction>),
  (name: "MEX／有效值域", function: "MEX 的有效值域", chapter: "工具与通用技巧", target: <book-mex>),
  (name: "不变量／下界构造", function: "可达性不变量与最优下界构造", chapter: "工具与通用技巧", target: <book-invariant-construction>),
  (name: "稀疏事件／时间跳跃", function: "稀疏事件跳过巨大时间轴", chapter: "工具与通用技巧", target: <book-sparse-events>),
  (name: "对拍／随机测试", function: "随机对拍", chapter: "工具与通用技巧", target: <book-stress-test>),
  (name: "单进程函数对拍", function: "单进程函数对拍", chapter: "工具与通用技巧", target: <book-variant-261>),
  (name: "进程对拍", function: "进程对拍", chapter: "工具与通用技巧", target: <book-variant-262>),
)
